### ISSUE TITLE
Typo in Module 6 Task 4

### ISSUE THREAD

**Issue by snychka** [pluralsight-projects/React-QuizComponent#10]
**Description:** Typo in [_Displaying An Error Message Based on State_'s >>
_Displaying an error message based on values in state_](https://app.pluralsight.com/projects/build-a-quiz-component-with-react/displaying-an-error-message-based-on-state/6b62a26f-c497-40f5-9c53-d97ba267cf72):

![screen shot 2018-07-10 at 2 46 58 pm](https://user-images.githubusercontent.com/5722849/42536829-6271239a-8450-11e8-906e-26b33c838f70.png)

- _tertiary_ ➡️ _ternary_
- Reported by Chandler Prince in course's Discussion tab

**Comment by jonfriskics** [comment]
Good catch - thanks @snychka and Chandler!  Fixed.
