### ISSUE TITLE
6.3 Typo, QuestQuestion

### ISSUE THREAD

**Issue by snychka** [pluralsight-projects/React-QuizComponent#20]
**location:** [6.3 Displaying An Error Message Based on State >> Changing state in QuestQuestion when a button is clicked](https://app.pluralsight.com/projects/build-a-quiz-component-with-react/displaying-an-error-message-based-on-state)

**issue:** QuestQuestion in task name/title should instead be QuizQuestion.

**screenshot:**

<img width="1194" alt="screen shot 2018-09-12 at 11 30 12 am" src="https://user-images.githubusercontent.com/5722849/45442482-5819fc80-b67f-11e8-90a0-be3bdc9fc539.png">

Reported by user.  @jonfriskics  (for me, Desk case 554946)

**Comment by jonfriskics** [comment]
fixed, thanks!
