### ISSUE TITLE
'CI' is not recognized.

### ISSUE THREAD

**Issue by flymason** [pluralsight-projects/React-QuizComponent#4]
During the initial setup, I ran into this problem when trying to run the tests. Do I need to install something extra for CI? The tests run if I remove "CI=true" from the **test** command under scripts in package.json.

$ npm run test

> build-a-quiz-component-with-react@0.1.0 test C:\src\pluralsight\React\React-QuizComponent
> CI=true ./node_modules/.bin/cross-env react-scripts test --env=jsdom --noStackTrace || true

'CI' is not recognized as an internal or external command,
operable program or batch file.

**Comment by jonfriskics** [comment]
Sorry about that - should be fixed in https://github.com/pluralsight-projects/React-QuizComponent/commit/2910c1b66aea57bef3145e5b2432b4bbe66a181b

**Comment by flymason** [comment]
Thank you! That fixed it.

**Comment by shaileshmca05** [comment]
Can any one help me please?? After initial setup, I ran into this problem when trying to run the test command.

PS C:\\ReactAndRedux\React-QuizComponent> npm run test

> build-a-quiz-component-with-react@0.1.1 test
> ./node_modules/.bin/cross-env CI=true react-scripts test --env=jsdom --noStackTrace || true

'.' is not recognized as an internal or external command,
operable program or batch file.
======================================================

My Node and NPM versions are
PS C:\ReactAndRedux\React-QuizComponent> node -v
v16.7.0
PS C:\ReactAndRedux\React-QuizComponent> npm -v
7.20.3

========================================

Package.json
-------------------
{
  "name": "build-a-quiz-component-with-react",
  "version": "0.1.1",
  "private": true,
  "dependencies": {
    "react": "16.2.0",
    "react-dom": "16.2.0",
    "react-scripts": "1.1.1"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "./node_modules/.bin/cross-env CI=true react-scripts test --env=jsdom --noStackTrace || true",
    "test:module1": "./node_modules/.bin/cross-env CI=true react-scripts test --env=jsdom --noStackTrace module1 || true",
    "test:module2": "./node_modules/.bin/cross-env CI=true react-scripts test --env=jsdom --noStackTrace module2 || true",
    "test:module3": "./node_modules/.bin/cross-env CI=true react-scripts test --env=jsdom --noStackTrace module3 || true",
    "test:module4": "./node_modules/.bin/cross-env CI=true react-scripts test --env=jsdom --noStackTrace module4 || true",
    "test:module5": "./node_modules/.bin/cross-env CI=true react-scripts test --env=jsdom --noStackTrace module5 || true",
    "test:module6": "./node_modules/.bin/cross-env CI=true react-scripts test --env=jsdom --noStackTrace module6 || true",
    "test:module7": "./node_modules/.bin/cross-env CI=true react-scripts test --env=jsdom --noStackTrace module7 || true",
    "eject": "react-scripts eject"
  },
  "jest": {
    "collectCoverageFrom": [
      "src/**/*.{js,jsx}",
      "!<rootDir>/node_modules/",
      "!<rootDir>/path/to/dir/"
    ],
    "coverageThreshold": {
      "global": {
        "branches": 90,
        "functions": 90,
        "lines": 90,
        "statements": 90
      }
    },
    "coverageReporters": [
      "json"
    ]
  },
  "devDependencies": {
    "babylon": "6.18.0",
    "chai": "4.1.2",
    "chai-enzyme": "0.8.0",
    "cross-env": "5.1.4",
    "enzyme": "3.3.0",
    "enzyme-adapter-react-16": "1.1.1",
    "esprima": "4.0.0",
    "react-test-renderer": "16.3.1",
    "sinon": "5.0.1"
  }
}

Thanks in advance.
