### ISSUE TITLE
No tests found for specific modules

### ISSUE THREAD

**Issue by flymason** [pluralsight-projects/React-QuizComponent#5]
When I try to run tests for a specific module, no tests match the pattern **src/__tests__/module#**. 

```
$ npm run test:module1

> build-a-quiz-component-with-react@0.1.1 test:module1 C:\src\pluralsight\React\React-QuizComponent
> cross-env CI=true react-scripts test --env=jsdom --noStackTrace src/__tests__/module1 || true

No tests found
In C:\src\pluralsight\React\React-QuizComponent
  62 files checked.
  testMatch: C:\src\pluralsight\React\React-QuizComponent\src\**\__tests__\**\*.{js,jsx,mjs},C:\src\pluralsight\React\React-QuizComponent\src\**\?(*.)(spec|test).{js,jsx,mjs} - 52 matches
  testPathIgnorePatterns: \\node_modules\\ - 62 matches
Pattern: "src/__tests__/module1" - 0 matches
```

The scripts work if you remove the leading directories from the pattern and just match on **module#**. Like this: 

`"test:module1": "./node_modules/.bin/cross-env CI=true react-scripts test --env=jsdom --noStackTrace module1 || true",`

**Comment by flymason** [comment]
@jonfriskics, if you agree to this fix, I'll make the change and create a pull request.

**Comment by jonfriskics** [comment]
go for it!
